-- MySQL Script generated by MySQL Workbench
-- Sun May 15 20:45:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema curriculo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curriculo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curriculo` DEFAULT CHARACTER SET utf8 ;
USE `curriculo` ;

-- -----------------------------------------------------
-- Table `curriculo`.`vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo`.`vagas` (
  `idvagas` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL,
  `salario` VARCHAR(15) NULL,
  `dataInicio` DATE NULL,
  `EscolaridadeExigida` INT NULL,
  PRIMARY KEY (`idvagas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculo`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculo`.`Candidato` (
  `idCandidato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `telefone` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `cpf` INT NULL,
  `escolaridade` VARCHAR(45) NULL,
  `vagas_idvagas` INT NOT NULL,
  PRIMARY KEY (`idCandidato`),
  INDEX `fk_Candidato_vagas_idx` (`vagas_idvagas` ASC) ,
  CONSTRAINT `fk_Candidato_vagas`
    FOREIGN KEY (`vagas_idvagas`)
    REFERENCES `curriculo`.`vagas` (`idvagas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
